import type {
  AuditEvent,
  CandidateDeprecationSnapshot,
  CandidateEventSnapshot,
  DownstreamDependency,
  EventDefinition,
  EventVersionSnapshot,
  GovernanceState,
  ReleaseCandidate,
} from './domain'

const events: EventDefinition[] = [
  {
    id: 'evt-001',
    key: 'trade_order_submit',
    displayName: '订单提交',
    category: '交易',
    description: '用户确认提交订单并进入支付前状态。',
    trigger: '订单确认按钮点击且创建订单成功',
    status: 'reviewing',
    version: '2.4.0',
    owner: '交易客户端组',
    properties: [
      {
        id: 'prop-001',
        eventId: 'evt-001',
        name: 'order_id',
        displayName: '订单号',
        type: 'string',
        required: true,
        description: '交易系统生成的唯一订单号。',
        enumValues: [],
        owner: '交易客户端组',
        synonyms: ['trade_id'],
        platforms: ['web', 'ios', 'android', 'server'],
        lineageSourceId: 'prop-021',
      },
      {
        id: 'prop-002',
        eventId: 'evt-001',
        name: 'amount',
        displayName: '订单金额',
        type: 'number',
        required: true,
        description: '订单应付金额，单位为分。',
        enumValues: [],
        owner: '交易客户端组',
        synonyms: ['order_amount'],
        platforms: ['web', 'ios', 'android', 'server'],
      },
      {
        id: 'prop-003',
        eventId: 'evt-001',
        name: 'currency',
        displayName: '币种',
        type: 'enum',
        required: true,
        description: '三字母 ISO 币种代码。',
        enumValues: ['CNY', 'USD', 'HKD'],
        owner: '交易客户端组',
        synonyms: [],
        platforms: ['web', 'ios', 'android', 'server'],
      },
      {
        id: 'prop-004',
        eventId: 'evt-001',
        name: 'coupon_id',
        displayName: '优惠券编号',
        type: 'string',
        required: false,
        description: '使用的优惠券编号。',
        enumValues: [],
        owner: '营销产品组',
        synonyms: ['promotion_id'],
        platforms: ['web', 'ios', 'android'],
      },
      {
        id: 'prop-005',
        eventId: 'evt-001',
        name: 'delivery_type',
        displayName: '配送类型',
        type: 'enum',
        required: true,
        description: '订单履约方式。',
        enumValues: ['express', 'pickup', 'virtual'],
        owner: '履约产品组',
        synonyms: ['fulfillment_type'],
        platforms: ['web', 'ios', 'android', 'server'],
      },
    ],
    platformRules: [
      {
        id: 'rule-001',
        eventId: 'evt-001',
        platform: 'web',
        enabled: true,
        trigger: '订单创建接口成功返回后上报',
        owner: 'Web 客户端组',
        requiredPropertyIds: ['prop-001', 'prop-002', 'prop-003', 'prop-005'],
        note: 'Web 端在支付弹窗打开前上报。',
      },
      {
        id: 'rule-002',
        eventId: 'evt-001',
        platform: 'ios',
        enabled: true,
        trigger: '订单确认页调用成功回调后上报',
        owner: 'iOS 客户端组',
        requiredPropertyIds: ['prop-001', 'prop-002', 'prop-003', 'prop-005'],
        note: 'iOS 端需要保持金额整数格式。',
      },
      {
        id: 'rule-003',
        eventId: 'evt-001',
        platform: 'android',
        enabled: true,
        trigger: '订单确认页调用成功回调后上报',
        owner: 'Android 客户端组',
        requiredPropertyIds: ['prop-001', 'prop-002', 'prop-003', 'prop-005'],
        note: 'Android 端允许离线补报，最多延迟 5 分钟。',
      },
      {
        id: 'rule-004',
        eventId: 'evt-001',
        platform: 'server',
        enabled: true,
        trigger: '订单服务发布领域事件后上报',
        owner: '交易服务组',
        requiredPropertyIds: ['prop-001', 'prop-002', 'prop-003', 'prop-005'],
        note: 'Server 侧作为最终去重口径。',
      },
    ],
    scenarioIds: ['scn-001', 'scn-002'],
    downstreamDependencyIds: ['dep-001', 'dep-002', 'dep-005'],
    updatedAt: '2026-09-26T15:20:00+08:00',
  },
  {
    id: 'evt-002',
    key: 'trade_order_pay_result',
    displayName: '支付结果',
    category: '交易',
    description: '支付渠道返回最终成功或失败结果。',
    trigger: '支付结果回调校验完成后',
    status: 'published',
    version: '2.1.0',
    owner: '支付平台组',
    properties: [
      {
        id: 'prop-006',
        eventId: 'evt-002',
        name: 'order_id',
        displayName: '订单号',
        type: 'string',
        required: true,
        description: '关联订单唯一编号。',
        enumValues: [],
        owner: '支付平台组',
        synonyms: ['trade_id'],
        platforms: ['web', 'ios', 'android', 'server'],
        lineageSourceId: 'prop-001',
      },
      {
        id: 'prop-007',
        eventId: 'evt-002',
        name: 'pay_result',
        displayName: '支付结果',
        type: 'enum',
        required: true,
        description: '支付渠道最终状态。',
        enumValues: ['success', 'failed', 'cancel'],
        owner: '支付平台组',
        synonyms: ['payment_status'],
        platforms: ['web', 'ios', 'android', 'server'],
      },
      {
        id: 'prop-008',
        eventId: 'evt-002',
        name: 'pay_channel',
        displayName: '支付渠道',
        type: 'enum',
        required: true,
        description: '用户选择或系统路由的渠道。',
        enumValues: ['alipay', 'wechat', 'card', 'balance'],
        owner: '支付平台组',
        synonyms: ['payment_channel'],
        platforms: ['web', 'ios', 'android', 'server'],
      },
      {
        id: 'prop-009',
        eventId: 'evt-002',
        name: 'failure_code',
        displayName: '失败原因码',
        type: 'string',
        required: false,
        description: '支付失败时的内部原因码。',
        enumValues: [],
        owner: '支付平台组',
        synonyms: ['error_code'],
        platforms: ['server'],
      },
    ],
    platformRules: [
      {
        id: 'rule-005',
        eventId: 'evt-002',
        platform: 'web',
        enabled: true,
        trigger: '支付结果页首次展示时上报',
        owner: 'Web 客户端组',
        requiredPropertyIds: ['prop-006', 'prop-007', 'prop-008'],
        note: '仅记录结果，不参与财务对账。',
      },
      {
        id: 'rule-006',
        eventId: 'evt-002',
        platform: 'ios',
        enabled: true,
        trigger: '支付 SDK 回调后上报',
        owner: 'iOS 客户端组',
        requiredPropertyIds: ['prop-006', 'prop-007', 'prop-008'],
        note: '不采集渠道原始错误信息。',
      },
      {
        id: 'rule-007',
        eventId: 'evt-002',
        platform: 'android',
        enabled: true,
        trigger: '支付 SDK 回调后上报',
        owner: 'Android 客户端组',
        requiredPropertyIds: ['prop-006', 'prop-007', 'prop-008'],
        note: '不采集渠道原始错误信息。',
      },
      {
        id: 'rule-008',
        eventId: 'evt-002',
        platform: 'server',
        enabled: true,
        trigger: '支付回调验签并幂等落库后上报',
        owner: '支付平台组',
        requiredPropertyIds: ['prop-006', 'prop-007', 'prop-008', 'prop-009'],
        note: 'Server 侧保留失败原因码。',
      },
    ],
    scenarioIds: ['scn-001'],
    downstreamDependencyIds: ['dep-002', 'dep-003'],
    updatedAt: '2026-09-22T10:12:00+08:00',
  },
  {
    id: 'evt-003',
    key: 'search_result_click',
    displayName: '搜索结果点击',
    category: '搜索',
    description: '用户点击搜索结果列表中的内容。',
    trigger: '结果卡片点击并准备跳转时',
    status: 'draft',
    version: '1.5.0',
    owner: '搜索产品组',
    properties: [
      {
        id: 'prop-010',
        eventId: 'evt-003',
        name: 'query_id',
        displayName: '查询编号',
        type: 'string',
        required: true,
        description: '本次搜索请求标识。',
        enumValues: [],
        owner: '搜索产品组',
        synonyms: ['search_id'],
        platforms: ['web', 'ios', 'android', 'server'],
      },
      {
        id: 'prop-011',
        eventId: 'evt-003',
        name: 'result_id',
        displayName: '结果编号',
        type: 'string',
        required: true,
        description: '被点击结果的内容编号。',
        enumValues: [],
        owner: '搜索产品组',
        synonyms: ['item_id'],
        platforms: ['web', 'ios', 'android', 'server'],
      },
      {
        id: 'prop-012',
        eventId: 'evt-003',
        name: 'position',
        displayName: '结果位置',
        type: 'number',
        required: true,
        description: '结果在列表中的序号，从 1 开始。',
        enumValues: [],
        owner: '搜索产品组',
        synonyms: ['rank'],
        platforms: ['web', 'ios', 'android'],
      },
      {
        id: 'prop-013',
        eventId: 'evt-003',
        name: 'click_type',
        displayName: '点击类型',
        type: 'enum',
        required: false,
        description: '点击发生的交互类型。',
        enumValues: ['tap', 'keyboard', 'voice'],
        owner: '搜索产品组',
        synonyms: ['interaction_type'],
        platforms: ['web', 'ios', 'android'],
      },
      {
        id: 'prop-014',
        eventId: 'evt-003',
        name: 'page_no',
        displayName: '页码',
        type: 'number',
        required: false,
        description: '结果所在页码。',
        enumValues: [],
        owner: '搜索产品组',
        synonyms: ['page_number'],
        platforms: ['web', 'ios', 'android'],
      },
    ],
    platformRules: [
      {
        id: 'rule-009',
        eventId: 'evt-003',
        platform: 'web',
        enabled: true,
        trigger: '结果跳转前同步上报',
        owner: 'Web 客户端组',
        requiredPropertyIds: ['prop-010', 'prop-011', 'prop-012'],
        note: '使用 keepalive 保证跳转前发送。',
      },
      {
        id: 'rule-010',
        eventId: 'evt-003',
        platform: 'ios',
        enabled: true,
        trigger: '结果页点击回调中上报',
        owner: 'iOS 客户端组',
        requiredPropertyIds: ['prop-010', 'prop-011', 'prop-012'],
        note: '位置从 1 开始。',
      },
      {
        id: 'rule-011',
        eventId: 'evt-003',
        platform: 'android',
        enabled: true,
        trigger: '结果页点击回调中上报',
        owner: 'Android 客户端组',
        requiredPropertyIds: ['prop-010', 'prop-011', 'prop-012'],
        note: '位置从 1 开始。',
      },
    ],
    scenarioIds: ['scn-003'],
    downstreamDependencyIds: ['dep-004'],
    updatedAt: '2026-09-28T09:35:00+08:00',
  },
  {
    id: 'evt-004',
    key: 'coupon_apply_result',
    displayName: '优惠券领取结果',
    category: '营销',
    description: '记录优惠券领取成功或失败。',
    trigger: '优惠券领取接口返回后',
    status: 'published',
    version: '3.0.0',
    owner: '营销产品组',
    properties: [
      {
        id: 'prop-015',
        eventId: 'evt-004',
        name: 'coupon_id',
        displayName: '优惠券编号',
        type: 'string',
        required: true,
        description: '优惠券模板编号。',
        enumValues: [],
        owner: '营销产品组',
        synonyms: ['promotion_id'],
        platforms: ['web', 'ios', 'android', 'server'],
      },
      {
        id: 'prop-016',
        eventId: 'evt-004',
        name: 'apply_result',
        displayName: '领取结果',
        type: 'enum',
        required: true,
        description: '优惠券领取状态。',
        enumValues: ['success', 'sold_out', 'not_eligible', 'error'],
        owner: '营销产品组',
        synonyms: ['coupon_status'],
        platforms: ['web', 'ios', 'android', 'server'],
      },
      {
        id: 'prop-017',
        eventId: 'evt-004',
        name: 'source_page',
        displayName: '来源页面',
        type: 'string',
        required: false,
        description: '领取行为发生的页面标识。',
        enumValues: [],
        owner: '营销产品组',
        synonyms: ['page_name'],
        platforms: ['web', 'ios', 'android'],
      },
    ],
    platformRules: [
      {
        id: 'rule-012',
        eventId: 'evt-004',
        platform: 'web',
        enabled: true,
        trigger: '领取结果弹窗展示时上报',
        owner: 'Web 客户端组',
        requiredPropertyIds: ['prop-015', 'prop-016'],
        note: '不采集用户设备信息。',
      },
      {
        id: 'rule-013',
        eventId: 'evt-004',
        platform: 'ios',
        enabled: true,
        trigger: '领取接口完成回调后上报',
        owner: 'iOS 客户端组',
        requiredPropertyIds: ['prop-015', 'prop-016'],
        note: '不采集用户设备信息。',
      },
      {
        id: 'rule-014',
        eventId: 'evt-004',
        platform: 'android',
        enabled: true,
        trigger: '领取接口完成回调后上报',
        owner: 'Android 客户端组',
        requiredPropertyIds: ['prop-015', 'prop-016'],
        note: '不采集用户设备信息。',
      },
      {
        id: 'rule-015',
        eventId: 'evt-004',
        platform: 'server',
        enabled: true,
        trigger: '领取事务提交后上报',
        owner: '营销服务组',
        requiredPropertyIds: ['prop-015', 'prop-016'],
        note: 'Server 侧作为最终口径。',
      },
    ],
    scenarioIds: ['scn-002'],
    downstreamDependencyIds: ['dep-001', 'dep-002'],
    updatedAt: '2026-09-18T11:40:00+08:00',
  },
  {
    id: 'evt-005',
    key: 'coupon_receive_result',
    displayName: '优惠券领取结果旧版',
    category: '营销',
    description: '历史优惠券领取事件，与 coupon_apply_result 语义重复。',
    trigger: '历史活动页领取完成后',
    status: 'deprecated',
    version: '1.2.0',
    owner: '营销产品组',
    properties: [
      {
        id: 'prop-018',
        eventId: 'evt-005',
        name: 'coupon_id',
        displayName: '优惠券编号',
        type: 'string',
        required: true,
        description: '优惠券模板编号。',
        enumValues: [],
        owner: '营销产品组',
        synonyms: ['promotion_id'],
        platforms: ['web', 'ios', 'android'],
      },
      {
        id: 'prop-019',
        eventId: 'evt-005',
        name: 'result',
        displayName: '领取结果',
        type: 'string',
        required: true,
        description: '历史字符串结果。',
        enumValues: [],
        owner: '营销产品组',
        synonyms: ['coupon_status'],
        platforms: ['web', 'ios', 'android'],
      },
      {
        id: 'prop-020',
        eventId: 'evt-005',
        name: 'source_page',
        displayName: '来源页面',
        type: 'string',
        required: false,
        description: '领取行为发生的页面。',
        enumValues: [],
        owner: '营销产品组',
        synonyms: ['page_name'],
        platforms: ['web', 'ios', 'android'],
      },
    ],
    platformRules: [
      {
        id: 'rule-016',
        eventId: 'evt-005',
        platform: 'web',
        enabled: false,
        trigger: '历史活动页领取完成后',
        owner: 'Web 客户端组',
        requiredPropertyIds: [],
        note: '已停止新采集。',
      },
      {
        id: 'rule-017',
        eventId: 'evt-005',
        platform: 'ios',
        enabled: false,
        trigger: '历史活动页领取完成后',
        owner: 'iOS 客户端组',
        requiredPropertyIds: [],
        note: '已停止新采集。',
      },
      {
        id: 'rule-018',
        eventId: 'evt-005',
        platform: 'android',
        enabled: false,
        trigger: '历史活动页领取完成后',
        owner: 'Android 客户端组',
        requiredPropertyIds: [],
        note: '已停止新采集。',
      },
    ],
    scenarioIds: ['scn-002'],
    downstreamDependencyIds: ['dep-006'],
    updatedAt: '2026-07-01T08:00:00+08:00',
  },
  {
    id: 'evt-006',
    key: 'profile_city_update',
    displayName: '收货城市更新',
    category: '用户',
    description: '配送地址中城市字段变化时上报。',
    trigger: '用户确认修改收货地址后',
    status: 'approved',
    version: '1.3.0',
    owner: '用户产品组',
    properties: [
      {
        id: 'prop-021',
        eventId: 'evt-006',
        name: 'user_id',
        displayName: '用户编号',
        type: 'string',
        required: true,
        description: '登录用户唯一编号。',
        enumValues: [],
        owner: '用户产品组',
        synonyms: ['member_id'],
        platforms: ['web', 'ios', 'android', 'server'],
      },
      {
        id: 'prop-022',
        eventId: 'evt-006',
        name: 'city_code',
        displayName: '城市编码',
        type: 'string',
        required: true,
        description: '标准行政区划编码。',
        enumValues: [],
        owner: '用户产品组',
        synonyms: ['delivery_city'],
        platforms: ['web', 'ios', 'android', 'server'],
      },
      {
        id: 'prop-023',
        eventId: 'evt-006',
        name: 'changed_from',
        displayName: '原城市编码',
        type: 'string',
        required: false,
        description: '变更前的城市编码。',
        enumValues: [],
        owner: '用户产品组',
        synonyms: ['old_city'],
        platforms: ['server'],
      },
    ],
    platformRules: [
      {
        id: 'rule-019',
        eventId: 'evt-006',
        platform: 'server',
        enabled: true,
        trigger: '地址更新事务提交后上报',
        owner: '用户服务组',
        requiredPropertyIds: ['prop-021', 'prop-022'],
        note: '原城市仅服务端保留。',
      },
      {
        id: 'rule-020',
        eventId: 'evt-006',
        platform: 'web',
        enabled: true,
        trigger: '地址保存成功后上报',
        owner: 'Web 客户端组',
        requiredPropertyIds: ['prop-021', 'prop-022'],
        note: '客户端不采集原城市。',
      },
    ],
    scenarioIds: ['scn-004'],
    downstreamDependencyIds: ['dep-006'],
    updatedAt: '2026-09-15T14:10:00+08:00',
  },
]

const dependencies: DownstreamDependency[] = [
  {
    id: 'dep-001',
    name: '交易转化实时看板',
    type: 'dashboard',
    owner: '数据产品组',
    environment: 'production',
    eventIds: ['evt-001', 'evt-004'],
    propertyRefs: [
      { eventId: 'evt-001', propertyId: 'prop-001' },
      { eventId: 'evt-001', propertyId: 'prop-002' },
      { eventId: 'evt-004', propertyId: 'prop-016' },
    ],
    status: 'active',
  },
  {
    id: 'dep-002',
    name: '支付失败率监控',
    type: 'alert',
    owner: 'SRE 数据组',
    environment: 'production',
    eventIds: ['evt-001', 'evt-002', 'evt-004'],
    propertyRefs: [
      { eventId: 'evt-002', propertyId: 'prop-007' },
      { eventId: 'evt-002', propertyId: 'prop-008' },
      { eventId: 'evt-004', propertyId: 'prop-016' },
    ],
    status: 'active',
  },
  {
    id: 'dep-003',
    name: '支付渠道转化模型',
    type: 'model',
    owner: '增长算法组',
    environment: 'analysis',
    eventIds: ['evt-002'],
    propertyRefs: [
      { eventId: 'evt-002', propertyId: 'prop-007' },
      { eventId: 'evt-002', propertyId: 'prop-008' },
      { eventId: 'evt-002', propertyId: 'prop-009' },
    ],
    status: 'active',
  },
  {
    id: 'dep-004',
    name: '搜索点击率报表',
    type: 'dataset',
    owner: '搜索数据组',
    environment: 'production',
    eventIds: ['evt-003'],
    propertyRefs: [
      { eventId: 'evt-003', propertyId: 'prop-010' },
      { eventId: 'evt-003', propertyId: 'prop-011' },
      { eventId: 'evt-003', propertyId: 'prop-012' },
      { eventId: 'evt-003', propertyId: 'prop-014' },
      { eventId: 'evt-003', propertyId: 'prop-024' },
    ],
    status: 'migration_required',
  },
  {
    id: 'dep-005',
    name: '优惠券归因实验',
    type: 'experiment',
    owner: '增长实验组',
    environment: 'analysis',
    eventIds: ['evt-001'],
    propertyRefs: [
      { eventId: 'evt-001', propertyId: 'prop-004' },
      { eventId: 'evt-001', propertyId: 'prop-005' },
    ],
    status: 'migration_required',
  },
  {
    id: 'dep-006',
    name: '历史优惠券口径兼容集',
    type: 'dataset',
    owner: '营销数据组',
    environment: 'analysis',
    eventIds: ['evt-005', 'evt-006'],
    propertyRefs: [
      { eventId: 'evt-005', propertyId: 'prop-019' },
      { eventId: 'evt-005', propertyId: 'prop-020' },
      { eventId: 'evt-006', propertyId: 'prop-023' },
    ],
    status: 'active',
  },
]

const baselines: EventVersionSnapshot[] = [
  {
    id: 'base-001',
    eventId: 'evt-001',
    version: '2.3.0',
    createdAt: '2026-08-15T10:00:00+08:00',
    status: 'published',
    properties: [
      {
        ...events[0]!.properties[0]!,
        type: 'number',
      },
      events[0]!.properties[1]!,
      events[0]!.properties[2]!,
      events[0]!.properties[3]!,
      events[0]!.properties[4]!,
    ],
  },
  {
    id: 'base-002',
    eventId: 'evt-002',
    version: '2.1.0',
    createdAt: '2026-08-12T10:00:00+08:00',
    status: 'published',
    properties: structuredClone(events[1]!.properties),
  },
  {
    id: 'base-003',
    eventId: 'evt-003',
    version: '1.4.0',
    createdAt: '2026-09-05T10:00:00+08:00',
    status: 'published',
    properties: [
      ...structuredClone(events[2]!.properties.filter((property) => property.id !== 'prop-014')),
      {
        ...events[2]!.properties.find((property) => property.id === 'prop-014')!,
        type: 'string',
      },
      {
        id: 'prop-024',
        eventId: 'evt-003',
        name: 'experiment_id',
        displayName: '实验编号',
        type: 'string',
        required: false,
        description: '旧版用于关联搜索实验。',
        enumValues: [],
        owner: '搜索产品组',
        synonyms: ['ab_test_id'],
        platforms: ['web', 'ios', 'android'],
        deletedAt: '2026-09-28T09:35:00+08:00',
      },
    ],
  },
  {
    id: 'base-004',
    eventId: 'evt-004',
    version: '3.0.0',
    createdAt: '2026-08-02T10:00:00+08:00',
    status: 'published',
    properties: structuredClone(events[3]!.properties),
  },
  {
    id: 'base-005',
    eventId: 'evt-006',
    version: '1.3.0',
    createdAt: '2026-08-20T10:00:00+08:00',
    status: 'published',
    properties: structuredClone(events[5]!.properties),
  },
]

const freezeSeedEvent = (eventId: string, frozenAt: string): CandidateEventSnapshot => {
  const event = events.find((item) => item.id === eventId)!
  return {
    eventId: event.id,
    key: event.key,
    displayName: event.displayName,
    category: event.category,
    description: event.description,
    trigger: event.trigger,
    status: event.status,
    version: event.version,
    owner: event.owner,
    properties: structuredClone(event.properties),
    platformRules: structuredClone(event.platformRules),
    frozenAt,
  }
}

const freezeSeedDeprecation = (
  planId: string,
  eventId: string,
  replacementEventId: string | undefined,
  status: 'planned' | 'announced' | 'stopped' | 'retired',
  stopCollectAt: string,
  retireAt: string,
  migrationNote: string,
  frozenAt: string,
): CandidateDeprecationSnapshot => ({
  planId,
  eventId,
  replacementEventId,
  status,
  stopCollectAt,
  retireAt,
  migrationNote,
  frozenAt,
})

const releases: ReleaseCandidate[] = [
  {
    id: 'rel-001',
    rev: 1,
    baseRevision: 7,
    version: '2026.10.0',
    title: '十月核心埋点契约升级',
    status: 'reviewing',
    eventIds: ['evt-001', 'evt-003', 'evt-005'],
    affectedDependencyIds: ['dep-001', 'dep-004', 'dep-005', 'dep-006'],
    differences: [
      {
        eventId: 'evt-001',
        eventKey: 'trade_order_submit',
        addedProperties: [],
        removedProperties: [],
        requiredChanges: ['order_id 必填规则仍需确认'],
        typeChanges: ['order_id: number → string'],
        enumChanges: [],
      },
      {
        eventId: 'evt-003',
        eventKey: 'search_result_click',
        addedProperties: [],
        removedProperties: [],
        requiredChanges: [],
        typeChanges: ['page_no: string → number'],
        enumChanges: ['click_type 新增 keyboard'],
      },
    ],
    migrationConfirmations: [
      {
        id: 'mig-001',
        epoch: 0,
        dependencyId: 'dep-001',
        version: '2026.10.0',
        status: 'pending',
        reviewer: '数据产品组',
        note: '',
      },
      {
        id: 'mig-002',
        epoch: 0,
        dependencyId: 'dep-004',
        version: '2026.10.0',
        status: 'confirmed',
        reviewer: '搜索数据组',
        note: '数据集已增加 page_no 数值转换。',
        confirmedAt: '2026-09-27T14:20:00+08:00',
      },
      {
        id: 'mig-003',
        epoch: 0,
        dependencyId: 'dep-005',
        version: '2026.10.0',
        status: 'pending',
        reviewer: '增长实验组',
        note: '等待实验口径冻结后确认。',
      },
      {
        id: 'mig-004',
        epoch: 0,
        dependencyId: 'dep-006',
        version: '2026.10.0',
        status: 'pending',
        reviewer: '营销数据组',
        note: '旧事件下线前保持只读兼容。',
      },
    ],
    approvals: [
      {
        id: 'appr-001',
        role: 'data',
        actor: '顾清',
        status: 'approved',
        comment: '指标口径影响已评估。',
        createdAt: '2026-09-27T16:00:00+08:00',
      },
      {
        id: 'appr-002',
        role: 'product',
        actor: '丁禾',
        status: 'pending',
        comment: '',
      },
      {
        id: 'appr-003',
        role: 'client',
        actor: '江驰',
        status: 'pending',
        comment: '',
      },
      {
        id: 'appr-004',
        role: 'qa',
        actor: '余安',
        status: 'pending',
        comment: '',
      },
    ],
    eventSnapshots: [
      freezeSeedEvent('evt-001', '2026-09-25T10:30:00+08:00'),
      freezeSeedEvent('evt-003', '2026-09-25T10:30:00+08:00'),
      freezeSeedEvent('evt-005', '2026-09-25T10:30:00+08:00'),
    ],
    deprecationSnapshots: [
      freezeSeedDeprecation(
        'plan-001',
        'evt-005',
        'evt-004',
        'announced',
        '2026-11-30',
        '2026-12-31',
        '历史活动页分批切换，兼容集保留只读映射至 2027 年 3 月。',
        '2026-09-25T10:30:00+08:00',
      ),
    ],
    createdAt: '2026-09-25T10:30:00+08:00',
  },
  {
    id: 'rel-000',
    rev: 1,
    baseRevision: 1,
    version: '2026.09.0',
    title: '九月埋点基线',
    status: 'published',
    eventIds: ['evt-002', 'evt-004', 'evt-006'],
    affectedDependencyIds: ['dep-002', 'dep-003'],
    differences: [],
    migrationConfirmations: [
      {
        id: 'mig-005',
        epoch: 0,
        dependencyId: 'dep-002',
        version: '2026.09.0',
        status: 'confirmed',
        reviewer: 'SRE 数据组',
        note: '监控规则已验证。',
        confirmedAt: '2026-08-29T15:00:00+08:00',
      },
      {
        id: 'mig-006',
        epoch: 0,
        dependencyId: 'dep-003',
        version: '2026.09.0',
        status: 'confirmed',
        reviewer: '增长算法组',
        note: '模型特征口径无变化。',
        confirmedAt: '2026-08-30T11:00:00+08:00',
      },
    ],
    approvals: [
      {
        id: 'appr-005',
        role: 'data',
        actor: '顾清',
        status: 'approved',
        comment: '通过。',
        createdAt: '2026-08-30T11:20:00+08:00',
      },
      {
        id: 'appr-006',
        role: 'product',
        actor: '丁禾',
        status: 'approved',
        comment: '通过。',
        createdAt: '2026-08-30T11:30:00+08:00',
      },
      {
        id: 'appr-007',
        role: 'client',
        actor: '江驰',
        status: 'approved',
        comment: '通过。',
        createdAt: '2026-08-30T11:40:00+08:00',
      },
      {
        id: 'appr-008',
        role: 'qa',
        actor: '余安',
        status: 'approved',
        comment: '示例校验通过。',
        createdAt: '2026-08-30T11:50:00+08:00',
      },
    ],
    eventSnapshots: [
      freezeSeedEvent('evt-002', '2026-08-25T09:00:00+08:00'),
      freezeSeedEvent('evt-004', '2026-08-25T09:00:00+08:00'),
      freezeSeedEvent('evt-006', '2026-08-25T09:00:00+08:00'),
    ],
    deprecationSnapshots: [],
    createdAt: '2026-08-25T09:00:00+08:00',
    publishedAt: '2026-08-30T12:00:00+08:00',
  },
]

const audit: AuditEvent[] = [
  {
    id: 'aud-001',
    entityType: 'release',
    entityId: 'rel-001',
    action: '创建发布候选',
    actor: '顾清',
    detail: '创建 2026.10.0，包含 3 个事件契约。',
    createdAt: '2026-09-25T10:30:00+08:00',
  },
  {
    id: 'aud-002',
    entityType: 'event',
    entityId: 'evt-003',
    action: '提交契约修订',
    actor: '江驰',
    detail: 'page_no 由 string 调整为 number，新增 keyboard 点击类型。',
    createdAt: '2026-09-28T09:35:00+08:00',
  },
  {
    id: 'aud-003',
    entityType: 'dependency',
    entityId: 'dep-004',
    action: '确认迁移',
    actor: '搜索数据组',
    detail: '搜索点击率报表已增加数值转换，确认兼容。',
    createdAt: '2026-09-27T14:20:00+08:00',
  },
  {
    id: 'aud-004',
    entityType: 'deprecation',
    entityId: 'plan-001',
    action: '发布废弃公告',
    actor: '营销产品组',
    detail: 'coupon_receive_result 计划于 2026-12-31 下线。',
    createdAt: '2026-09-20T16:10:00+08:00',
  },
]

export const createSeedState = (): GovernanceState => ({
  events,
  scenarios: [
    {
      id: 'scn-001',
      name: '下单支付主链路',
      domain: '交易',
      owner: '交易产品组',
      platform: 'web',
      eventIds: ['evt-001', 'evt-002'],
      status: 'active',
    },
    {
      id: 'scn-002',
      name: '营销领券转化',
      domain: '营销',
      owner: '营销产品组',
      platform: 'ios',
      eventIds: ['evt-001', 'evt-004', 'evt-005'],
      status: 'migrating',
    },
    {
      id: 'scn-003',
      name: '搜索结果优化',
      domain: '搜索',
      owner: '搜索产品组',
      platform: 'android',
      eventIds: ['evt-003'],
      status: 'active',
    },
    {
      id: 'scn-004',
      name: '用户城市画像',
      domain: '用户',
      owner: '用户产品组',
      platform: 'server',
      eventIds: ['evt-006'],
      status: 'active',
    },
  ],
  dependencies,
  baselines,
  releases,
  deprecations: [
    {
      id: 'plan-001',
      rev: 1,
      eventId: 'evt-005',
      replacementEventId: 'evt-004',
      reason: '与 coupon_apply_result 语义重复，维护两套口径增加数据成本。',
      owner: '营销产品组',
      stopCollectAt: '2026-11-30',
      retireAt: '2026-12-31',
      status: 'announced',
      migrationNote: '历史活动页分批切换，兼容集保留只读映射至 2027 年 3 月。',
      updatedAt: '2026-09-20T16:10:00+08:00',
    },
  ],
  rollbacks: [
    {
      id: 'rollback-001',
      releaseId: 'rel-legacy-008',
      version: '2026.08.1',
      reason: 'Android 端 page_no 传参格式错误导致搜索报表异常。',
      operator: '江驰',
      scope: 'Android 2.18.0 至 2.18.2',
      createdAt: '2026-08-19T18:20:00+08:00',
      status: 'verified',
      evidence: 'RPT-INCIDENT-8821 / MOBILE-REL-2026-0819',
    },
  ],
  audit,
  currentVersion: '2026.10.0',
})
